language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rulguti/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rulguti/docker-react npm run test
