language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rulguti/docker-react -f Dockerfile.dev . 

script:
<<<<<<< HEAD
#  - docker run rulguti/docker-react npm run test -- --coverage
  - docker run -e CI=true rulguti/docker-react npm run test
=======
  - docker run rulguti/docker-react npm run test -- --coverage
>>>>>>> df755d6d0714e8d4616e77089a0ec443ddb0d9c8
